{-# OPTIONS_GHC -fno-warn-incomplete-patterns #-}
module PrintGramatyka where

-- pretty-printer generated by the BNF converter

import AbsGramatyka
import Data.Char


-- the top-level printing method
printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 (map ($ "") $ d []) "" where
  rend i ss = case ss of
    "["      :ts -> showChar '[' . rend i ts
    "("      :ts -> showChar '(' . rend i ts
    "{"      :ts -> showChar '{' . new (i+1) . rend (i+1) ts
    "}" : ";":ts -> new (i-1) . space "}" . showChar ';' . new (i-1) . rend (i-1) ts
    "}"      :ts -> new (i-1) . showChar '}' . new (i-1) . rend (i-1) ts
    ";"      :ts -> showChar ';' . new i . rend i ts
    t  : "," :ts -> showString t . space "," . rend i ts
    t  : ")" :ts -> showString t . showChar ')' . rend i ts
    t  : "]" :ts -> showString t . showChar ']' . rend i ts
    t        :ts -> space t . rend i ts
    _            -> id
  new i   = showChar '\n' . replicateS (2*i) (showChar ' ') . dropWhile isSpace
  space t = showString t . (\s -> if null s then "" else (' ':s))

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- the printer class does the job
class Print a where
  prt :: Int -> a -> Doc
  prtList :: Int -> [a] -> Doc
  prtList i = concatD . map (prt i)

instance Print a => Print [a] where
  prt = prtList

instance Print Char where
  prt _ s = doc (showChar '\'' . mkEsc '\'' s . showChar '\'')
  prtList _ s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q s = case s of
  _ | s == q -> showChar '\\' . showChar s
  '\\'-> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  _ -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j<i then parenth else id


instance Print Integer where
  prt _ x = doc (shows x)


instance Print Double where
  prt _ x = doc (shows x)


instance Print Ident where
  prt _ (Ident i) = doc (showString ( i))



instance Print Program where
  prt i e = case e of
    Prog topstms -> prPrec i 0 (concatD [prt 0 topstms])
    ProExp exp -> prPrec i 0 (concatD [prt 0 exp])

instance Print Type where
  prt i e = case e of
    IntType -> prPrec i 0 (concatD [doc (showString "int")])
    StrType -> prPrec i 0 (concatD [doc (showString "string")])
    BoolType -> prPrec i 0 (concatD [doc (showString "bool")])
    VoidType -> prPrec i 0 (concatD [doc (showString "void")])

instance Print Ref where
  prt i e = case e of
    IntRef -> prPrec i 0 (concatD [doc (showString "int&")])
    StrRef -> prPrec i 0 (concatD [doc (showString "string&")])
    BoolRef -> prPrec i 0 (concatD [doc (showString "bool&")])

instance Print Exp where
  prt i e = case e of
    EStr str -> prPrec i 6 (concatD [prt 0 str])
    EIdent id -> prPrec i 6 (concatD [prt 0 id])
    ERef id -> prPrec i 6 (concatD [doc (showString "&"), prt 0 id])
    EFun id exps -> prPrec i 6 (concatD [prt 0 id, doc (showString "("), prt 0 exps, doc (showString ")")])
    EInt n -> prPrec i 6 (concatD [prt 0 n])
    Neg exp -> prPrec i 5 (concatD [doc (showString "-"), prt 6 exp])
    EMul exp1 mulop exp2 -> prPrec i 4 (concatD [prt 4 exp1, prt 0 mulop, prt 5 exp2])
    EAdd exp1 addop exp2 -> prPrec i 3 (concatD [prt 3 exp1, prt 0 addop, prt 4 exp2])
    ETrue -> prPrec i 6 (concatD [doc (showString "true")])
    EFalse -> prPrec i 6 (concatD [doc (showString "false")])
    Not exp -> prPrec i 5 (concatD [doc (showString "!"), prt 6 exp])
    ERel exp1 relop exp2 -> prPrec i 2 (concatD [prt 2 exp1, prt 0 relop, prt 3 exp2])
    EAnd exp1 exp2 -> prPrec i 1 (concatD [prt 2 exp1, doc (showString "&&"), prt 1 exp2])
    EOr exp1 exp2 -> prPrec i 0 (concatD [prt 1 exp1, doc (showString "||"), prt 0 exp2])
  prtList _ [] = (concatD [])
  prtList _ [x] = (concatD [prt 0 x])
  prtList _ (x:xs) = (concatD [prt 0 x, doc (showString ","), prt 0 xs])
instance Print AddOp where
  prt i e = case e of
    Plus -> prPrec i 0 (concatD [doc (showString "+")])
    Minus -> prPrec i 0 (concatD [doc (showString "-")])

instance Print MulOp where
  prt i e = case e of
    Times -> prPrec i 0 (concatD [doc (showString "*")])
    Div -> prPrec i 0 (concatD [doc (showString "/")])
    Mod -> prPrec i 0 (concatD [doc (showString "%")])

instance Print RelOp where
  prt i e = case e of
    LTH -> prPrec i 0 (concatD [doc (showString "<")])
    LE -> prPrec i 0 (concatD [doc (showString "<=")])
    GTH -> prPrec i 0 (concatD [doc (showString ">")])
    GE -> prPrec i 0 (concatD [doc (showString ">=")])
    EQU -> prPrec i 0 (concatD [doc (showString "==")])
    NE -> prPrec i 0 (concatD [doc (showString "!=")])

instance Print TopStm where
  prt i e = case e of
    DeclTop type_ items -> prPrec i 0 (concatD [prt 0 type_, prt 0 items, doc (showString ";")])
    FunDecTop fun -> prPrec i 0 (concatD [prt 0 fun, doc (showString ";")])
    FunDefTop fun block -> prPrec i 0 (concatD [prt 0 fun, prt 0 block])
  prtList _ [] = (concatD [])
  prtList _ (x:xs) = (concatD [prt 0 x, prt 0 xs])
instance Print Stm where
  prt i e = case e of
    Decl type_ items -> prPrec i 0 (concatD [prt 0 type_, prt 0 items, doc (showString ";")])
    Ass id exp -> prPrec i 0 (concatD [prt 0 id, doc (showString "="), prt 0 exp, doc (showString ";")])
    Cond exp block -> prPrec i 0 (concatD [doc (showString "if"), doc (showString "("), prt 0 exp, doc (showString ")"), prt 0 block])
    CondElse exp block1 block2 -> prPrec i 0 (concatD [doc (showString "if"), doc (showString "("), prt 0 exp, doc (showString ")"), prt 0 block1, doc (showString "else"), prt 0 block2])
    While exp block -> prPrec i 0 (concatD [doc (showString "while"), doc (showString "("), prt 0 exp, doc (showString ")"), prt 0 block])
    StmExp exp -> prPrec i 0 (concatD [prt 0 exp, doc (showString ";")])
    Print exps -> prPrec i 0 (concatD [doc (showString "print"), doc (showString "("), prt 0 exps, doc (showString ")"), doc (showString ";")])
    FunDec fun -> prPrec i 0 (concatD [prt 0 fun, doc (showString ";")])
    FunDef fun block -> prPrec i 0 (concatD [prt 0 fun, prt 0 block])
    RetVal exp -> prPrec i 0 (concatD [doc (showString "return"), prt 0 exp, doc (showString ";")])
    Ret -> prPrec i 0 (concatD [doc (showString "return"), doc (showString ";")])
  prtList _ [] = (concatD [])
  prtList _ (x:xs) = (concatD [prt 0 x, prt 0 xs])
instance Print Item where
  prt i e = case e of
    NoInit id -> prPrec i 0 (concatD [prt 0 id])
    Init id exp -> prPrec i 0 (concatD [prt 0 id, doc (showString "="), prt 0 exp])
  prtList _ [x] = (concatD [prt 0 x])
  prtList _ (x:xs) = (concatD [prt 0 x, doc (showString ","), prt 0 xs])
instance Print Block where
  prt i e = case e of
    Blk stms -> prPrec i 0 (concatD [doc (showString "{"), prt 0 stms, doc (showString "}")])

instance Print Arg where
  prt i e = case e of
    ArgType type_ id -> prPrec i 0 (concatD [prt 0 type_, prt 0 id])
    ArgRef ref id -> prPrec i 0 (concatD [prt 0 ref, prt 0 id])
  prtList _ [] = (concatD [])
  prtList _ [x] = (concatD [prt 0 x])
  prtList _ (x:xs) = (concatD [prt 0 x, doc (showString ","), prt 0 xs])
instance Print Fun where
  prt i e = case e of
    FunPref type_ id args -> prPrec i 0 (concatD [prt 0 type_, prt 0 id, doc (showString "("), prt 0 args, doc (showString ")")])


